# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/fraud_detection
spring.datasource.username=root
spring.datasource.password=Chinni@4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server (KEEP ONLY ONE)
server.port=5000

# File Upload
spring.servlet.multipart.enabled=true